# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='nama',
            field=models.CharField(default='Mobil X', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peminjamankendaraan',
            name='odometer_sebelum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='peminjamankendaraan',
            name='odometer_sesudah',
            field=models.FloatField(null=True),
        ),
    ]
