# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0003_mobil_supir'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMobil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='/kendaraan')),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Mobil')),
            ],
        ),
    ]
