# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0004_fotomobil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotomobil',
            name='foto',
            field=models.ImageField(upload_to='kendaraan/'),
        ),
    ]
