# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0005_auto_20170415_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='foto_bukti_transfer',
            field=models.ImageField(default=None, upload_to='bukti transfer peminjaman/'),
            preserve_default=False,
        ),
    ]
