# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0006_peminjamankendaraan_foto_bukti_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='waktu_berangkat',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='waktu_datang',
            field=models.TimeField(default='00:00'),
        ),
    ]
