# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0007_auto_20170428_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='foto_form_akhir',
            field=models.ImageField(default=None, upload_to='bukti form akhir/'),
            preserve_default=False,
        ),
    ]
