# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0008_peminjamankendaraan_foto_form_akhir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleponpeminjam',
            name='peminjam',
        ),
        migrations.RemoveField(
            model_name='peminjamankendaraan',
            name='peminjam',
        ),
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='nama_peminjam',
            field=models.CharField(default='haha', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='no_telp_peminjam',
            field=models.CharField(default='123456789', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Peminjam',
        ),
        migrations.DeleteModel(
            name='TeleponPeminjam',
        ),
    ]
