# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0009_auto_20180227_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilPeminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Mobil')),
            ],
        ),
        migrations.RemoveField(
            model_name='peminjamankendaraan',
            name='bukti_transfer',
        ),
        migrations.RemoveField(
            model_name='peminjamankendaraan',
            name='foto_bukti_transfer',
        ),
        migrations.RemoveField(
            model_name='peminjamankendaraan',
            name='foto_form_akhir',
        ),
        migrations.RemoveField(
            model_name='peminjamankendaraan',
            name='mobil',
        ),
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='bagian_jurusan_peminjam',
            field=models.CharField(default='hai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilpeminjaman',
            name='peminjaman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.PeminjamanKendaraan'),
        ),
    ]
