# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0010_auto_20180303_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjamankendaraan',
            name='supir',
        ),
    ]
