# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0012_auto_20180304_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilpeminjaman',
            name='odometer_sebelum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mobilpeminjaman',
            name='odometer_sesudah',
            field=models.FloatField(null=True),
        ),
    ]
