# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0014_mobilpeminjaman_supir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilpeminjaman',
            name='supir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Supir'),
        ),
    ]
