# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0015_auto_20180312_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobil',
            name='supir',
        ),
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='foto_bukti_transfer',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
