# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0016_auto_20180312_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamankendaraan',
            name='foto_bukti_transfer',
            field=models.ImageField(null=True, upload_to='bukti_transfer/'),
        ),
    ]
