# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0017_auto_20180316_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamankendaraan',
            name='metode_transfer',
            field=models.IntegerField(null=True),
        ),
    ]
