# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0018_peminjamankendaraan_metode_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerkiraanBiaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.ImageField(upload_to='perkiraan_biaya/')),
            ],
        ),
    ]
