# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0019_perkiraanbiaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perkiraanbiaya',
            name='pdf',
            field=models.FileField(upload_to='perkiraan_biaya/'),
        ),
    ]
