# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0020_peminjamankendaraan_email_peminjam'),
        ('peminjaman', '0020_auto_20180330_1237'),
    ]

    operations = [
    ]
