# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0022_auto_20180411_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamankendaraan',
            name='bagian_jurusan_peminjam',
            field=models.IntegerField(choices=[(0, 'FITB'), (1, 'FMIPA'), (2, 'FSRD'), (3, 'FTI'), (4, 'FTMD'), (5, 'FTTM'), (6, 'FTSL'), (7, 'SAPPK'), (8, 'SBM'), (9, 'SF'), (10, 'SITH'), (11, 'STEI'), (12, 'Other')]),
        ),
    ]
